language: bash
sudo: required
services: docker
env:
  global:
    - CACHE_DIR=$HOME/.cache/docker
    - CACHE_FILE_CROSSBUILD=$CACHE_DIR/crossbuild.tar.gz
    - secure: ch+xO3Uy/BlDURTBeLTh28vrdAgsD65EvueJDe/X8zoCWMbLZAHw9kVT7YQH8WSn3QBWbCNuRW/yFSt+j+Y48c+4tFuzaFaxwRXqGBzhbjxleT3aIGgkoa3xU9+WnbsV4HfRCSzd4yfN08jN0Ob8/fmN1poQJeGsQj46yfhJe9/AT52CSeI+v/fYLDzou8FfzOakDAPOyYQpLmUHrX4vrXTZWPmgqCYytrl8o0GmobGAHYMskL2KXaTV4VmyoKmVFpRlhPL7rgbqcoZ0GTI7RCG5UY0cMIGUnwD6h6/A4XveP6KhcL9tWs3iJXt0MlkYAy6RXuNgSrKZjjHd1Atx1h65k6c2p5++OqVpnCBdKq49eHpUOeiP2/UuOytDtzHZzSr/sQRRYfA6ImvdGg1d8UorXSAtxGljNGS2hvqq4oYbP4eWGbAvczB3Pw/YUT2sLk89BEp3gK0QrjGvg6wR59ywuDUksGloBeFYsMqWx2XAMeup9r1clCybuAubZdKYjb/rynoPOhvcFYidMa6xylpMzz23L6PXT0qxbgfnxyB6cIAOhifS17E/KuaxaRSLez0/AhZK4YgoKr47HGN8ntl5i3UdLpkfXluqJWyq0LH0C8ULkQdJEfSvyzJO+hNS7muoOHgRLziP9tSDIkZf1krHdaFJXwOUSp32R1xS/SQ=
  matrix:
    - DIST=amd64 ARCH=x86_64 CROSS=x86_64-linux-gnu RELEASE=1
    - DIST=armhf ARCH=armeabi-v7a CROSS=arm-linux-gnueabihf RELEASE=1
    - DIST=arm64 ARCH=arm64 CROSS=aarch64-linux-gnu RELEASE=1
    - DIST=amd64 ARCH=x86_64 CROSS=x86_64-linux-gnu RELEASE=0
    - DIST=armhf ARCH=armeabi-v7a CROSS=arm-linux-gnueabihf RELEASE=0
    - DIST=arm64 ARCH=arm64 CROSS=aarch64-linux-gnu RELEASE=0

cache:
  directories:
    - $CACHE_DIR

before_install:
  - if [ -f ${CACHE_FILE_CROSSBUILD} ]; then gunzip -c ${CACHE_FILE_CROSSBUILD} | docker load; fi
  - docker images

install:
  - docker run --rm multiarch/crossbuild
  - if [ ! -f ${CACHE_FILE_CROSSBUILD} ]; then docker save multiarch/crossbuild | gzip > ${CACHE_FILE_CROSSBUILD}; fi
  - sudo apt-get -y install qemu-user-static sed

script:
  - ./build.sh $DIST $ARCH $CROSS $RELEASE

before_deploy:
  - docker images
  - docker login -u webispy -p $DOCKER_PASS

deploy:
  provider: script
  script: docker push webispy/iotivity
